package mapper.user;

import entity.user.Detail;
import entity.user.DetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DetailMapper {

    List<Detail> selectOrderDetailByOrderId(Integer orderId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_detail
     *
     * @mbg.generated
     */
    long countByExample(DetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_detail
     *
     * @mbg.generated
     */
    int deleteByExample(DetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_detail
     *
     * @mbg.generated
     */
    int insert(Detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_detail
     *
     * @mbg.generated
     */
    int insertSelective(Detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_detail
     *
     * @mbg.generated
     */
    List<Detail> selectByExample(DetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_detail
     *
     * @mbg.generated
     */
    Detail selectByPrimaryKey(Integer detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Detail record, @Param("example") DetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Detail record, @Param("example") DetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Detail record);
}