package mapper.staff;

import entity.staff.Cardetail;
import entity.staff.CardetailExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CardetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_cardetail
     *
     * @mbg.generated
     */
    long countByExample(CardetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_cardetail
     *
     * @mbg.generated
     */
    int deleteByExample(CardetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_cardetail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cardetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_cardetail
     *
     * @mbg.generated
     */
    int insert(Cardetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_cardetail
     *
     * @mbg.generated
     */
    int insertSelective(Cardetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_cardetail
     *
     * @mbg.generated
     */
    List<Cardetail> selectByExample(CardetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_cardetail
     *
     * @mbg.generated
     */
    Cardetail selectByPrimaryKey(Integer cardetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_cardetail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Cardetail record, @Param("example") CardetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_cardetail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Cardetail record, @Param("example") CardetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_cardetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Cardetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_cardetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cardetail record);
}