package mapper.staff;

import entity.staff.Locationdetail;
import entity.staff.LocationdetailExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LocationdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_locationdetail
     *
     * @mbg.generated
     */
    long countByExample(LocationdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_locationdetail
     *
     * @mbg.generated
     */
    int deleteByExample(LocationdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_locationdetail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer ldetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_locationdetail
     *
     * @mbg.generated
     */
    int insert(Locationdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_locationdetail
     *
     * @mbg.generated
     */
    int insertSelective(Locationdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_locationdetail
     *
     * @mbg.generated
     */
    List<Locationdetail> selectByExample(LocationdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_locationdetail
     *
     * @mbg.generated
     */
    Locationdetail selectByPrimaryKey(Integer ldetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_locationdetail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Locationdetail record, @Param("example") LocationdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_locationdetail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Locationdetail record, @Param("example") LocationdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_locationdetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Locationdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_locationdetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Locationdetail record);
}