package mapper.staff;

import entity.staff.Location;
import entity.staff.LocationExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_location
     *
     * @mbg.generated
     */
    long countByExample(LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_location
     *
     * @mbg.generated
     */
    int deleteByExample(LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_location
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer locationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_location
     *
     * @mbg.generated
     */
    int insert(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_location
     *
     * @mbg.generated
     */
    int insertSelective(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_location
     *
     * @mbg.generated
     */
    List<Location> selectByExample(LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_location
     *
     * @mbg.generated
     */
    Location selectByPrimaryKey(Integer locationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_location
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Location record, @Param("example") LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_location
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Location record, @Param("example") LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_location
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_location
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Location record);
}