package entity.user;

public class Detail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_detail.detail_id
     *
     * @mbg.generated
     */
    private Integer detailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_detail.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_detail.good_id
     *
     * @mbg.generated
     */
    private Integer goodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_detail.good_num
     *
     * @mbg.generated
     */
    private Integer goodNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_detail.detail_id
     *
     * @return the value of l_detail.detail_id
     *
     * @mbg.generated
     */
    public Integer getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_detail.detail_id
     *
     * @param detailId the value for l_detail.detail_id
     *
     * @mbg.generated
     */
    public void setDetailId(Integer detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_detail.order_id
     *
     * @return the value of l_detail.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_detail.order_id
     *
     * @param orderId the value for l_detail.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_detail.good_id
     *
     * @return the value of l_detail.good_id
     *
     * @mbg.generated
     */
    public Integer getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_detail.good_id
     *
     * @param goodId the value for l_detail.good_id
     *
     * @mbg.generated
     */
    public void setGoodId(Integer goodId) {
        this.goodId = goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_detail.good_num
     *
     * @return the value of l_detail.good_num
     *
     * @mbg.generated
     */
    public Integer getGoodNum() {
        return goodNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_detail.good_num
     *
     * @param goodNum the value for l_detail.good_num
     *
     * @mbg.generated
     */
    public void setGoodNum(Integer goodNum) {
        this.goodNum = goodNum;
    }

    @Override
    public String toString() {
        return "Detail{" +
                "detailId=" + detailId +
                ", orderId=" + orderId +
                ", goodId=" + goodId +
                ", goodNum=" + goodNum +
                '}';
    }
}