package entity.user;

import java.util.Date;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_goods.good_id
     *
     * @mbg.generated
     */
    private Integer goodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_goods.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_goods.detail
     *
     * @mbg.generated
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_goods.pic
     *
     * @mbg.generated
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_goods.price
     *
     * @mbg.generated
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_goods.size
     *
     * @mbg.generated
     */
    private Integer size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_goods.ex_number
     *
     * @mbg.generated
     */
    private Integer exNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_goods.sa_number
     *
     * @mbg.generated
     */
    private Integer saNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_goods.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_goods.good_name
     *
     * @mbg.generated
     */
    private String goodName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_goods.good_id
     *
     * @return the value of l_goods.good_id
     *
     * @mbg.generated
     */
    public Integer getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_goods.good_id
     *
     * @param goodId the value for l_goods.good_id
     *
     * @mbg.generated
     */
    public void setGoodId(Integer goodId) {
        this.goodId = goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_goods.createtime
     *
     * @return the value of l_goods.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_goods.createtime
     *
     * @param createtime the value for l_goods.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_goods.detail
     *
     * @return the value of l_goods.detail
     *
     * @mbg.generated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_goods.detail
     *
     * @param detail the value for l_goods.detail
     *
     * @mbg.generated
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_goods.pic
     *
     * @return the value of l_goods.pic
     *
     * @mbg.generated
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_goods.pic
     *
     * @param pic the value for l_goods.pic
     *
     * @mbg.generated
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_goods.price
     *
     * @return the value of l_goods.price
     *
     * @mbg.generated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_goods.price
     *
     * @param price the value for l_goods.price
     *
     * @mbg.generated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_goods.size
     *
     * @return the value of l_goods.size
     *
     * @mbg.generated
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_goods.size
     *
     * @param size the value for l_goods.size
     *
     * @mbg.generated
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_goods.ex_number
     *
     * @return the value of l_goods.ex_number
     *
     * @mbg.generated
     */
    public Integer getExNumber() {
        return exNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_goods.ex_number
     *
     * @param exNumber the value for l_goods.ex_number
     *
     * @mbg.generated
     */
    public void setExNumber(Integer exNumber) {
        this.exNumber = exNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_goods.sa_number
     *
     * @return the value of l_goods.sa_number
     *
     * @mbg.generated
     */
    public Integer getSaNumber() {
        return saNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_goods.sa_number
     *
     * @param saNumber the value for l_goods.sa_number
     *
     * @mbg.generated
     */
    public void setSaNumber(Integer saNumber) {
        this.saNumber = saNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_goods.type
     *
     * @return the value of l_goods.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_goods.type
     *
     * @param type the value for l_goods.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_goods.good_name
     *
     * @return the value of l_goods.good_name
     *
     * @mbg.generated
     */
    public String getGoodName() {
        return goodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_goods.good_name
     *
     * @param goodName the value for l_goods.good_name
     *
     * @mbg.generated
     */
    public void setGoodName(String goodName) {
        this.goodName = goodName;
    }
}