package entity.user;

public class Myself {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_myself.myself_id
     *
     * @mbg.generated
     */
    private Integer myselfId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_myself.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_myself.hobby
     *
     * @mbg.generated
     */
    private String hobby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_myself.signature
     *
     * @mbg.generated
     */
    private String signature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_myself.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_myself.myself_id
     *
     * @return the value of l_myself.myself_id
     *
     * @mbg.generated
     */
    public Integer getMyselfId() {
        return myselfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_myself.myself_id
     *
     * @param myselfId the value for l_myself.myself_id
     *
     * @mbg.generated
     */
    public void setMyselfId(Integer myselfId) {
        this.myselfId = myselfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_myself.uid
     *
     * @return the value of l_myself.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_myself.uid
     *
     * @param uid the value for l_myself.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_myself.hobby
     *
     * @return the value of l_myself.hobby
     *
     * @mbg.generated
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_myself.hobby
     *
     * @param hobby the value for l_myself.hobby
     *
     * @mbg.generated
     */
    public void setHobby(String hobby) {
        this.hobby = hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_myself.signature
     *
     * @return the value of l_myself.signature
     *
     * @mbg.generated
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_myself.signature
     *
     * @param signature the value for l_myself.signature
     *
     * @mbg.generated
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_myself.username
     *
     * @return the value of l_myself.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_myself.username
     *
     * @param username the value for l_myself.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String toString() {
        return "Myself{" +
                "myselfId=" + myselfId +
                ", uid=" + uid +
                ", hobby='" + hobby + '\'' +
                ", signature='" + signature + '\'' +
                ", username='" + username + '\'' +
                '}';
    }
}