package entity.user;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_order.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_order.u_id
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_order.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_order.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_order.address_id
     *
     * @mbg.generated
     */
    private Integer addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_order.cardetail_id
     *
     * @mbg.generated
     */
    private Integer cardetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_order.size
     *
     * @mbg.generated
     */
    private Integer size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_order.startpoint
     *
     * @mbg.generated
     */
    private String startpoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_order.destination
     *
     * @mbg.generated
     */
    private String destination;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_order.totalprice
     *
     * @mbg.generated
     */
    private Double totalprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_order.order_id
     *
     * @return the value of l_order.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_order.order_id
     *
     * @param orderId the value for l_order.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_order.u_id
     *
     * @return the value of l_order.u_id
     *
     * @mbg.generated
     */
    public Integer getuid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_order.u_id
     *
     * @param uid the value for l_order.u_id
     *
     * @mbg.generated
     */
    public void setuid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_order.createtime
     *
     * @return the value of l_order.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_order.createtime
     *
     * @param createtime the value for l_order.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_order.status
     *
     * @return the value of l_order.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_order.status
     *
     * @param status the value for l_order.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_order.address_id
     *
     * @return the value of l_order.address_id
     *
     * @mbg.generated
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_order.address_id
     *
     * @param addressId the value for l_order.address_id
     *
     * @mbg.generated
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_order.cardetail_id
     *
     * @return the value of l_order.cardetail_id
     *
     * @mbg.generated
     */
    public Integer getCardetailId() {
        return cardetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_order.cardetail_id
     *
     * @param cardetailId the value for l_order.cardetail_id
     *
     * @mbg.generated
     */
    public void setCardetailId(Integer cardetailId) {
        this.cardetailId = cardetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_order.size
     *
     * @return the value of l_order.size
     *
     * @mbg.generated
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_order.size
     *
     * @param size the value for l_order.size
     *
     * @mbg.generated
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_order.startpoint
     *
     * @return the value of l_order.startpoint
     *
     * @mbg.generated
     */
    public String getStartpoint() {
        return startpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_order.startpoint
     *
     * @param startpoint the value for l_order.startpoint
     *
     * @mbg.generated
     */
    public void setStartpoint(String startpoint) {
        this.startpoint = startpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_order.destination
     *
     * @return the value of l_order.destination
     *
     * @mbg.generated
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_order.destination
     *
     * @param destination the value for l_order.destination
     *
     * @mbg.generated
     */
    public void setDestination(String destination) {
        this.destination = destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_order.totalprice
     *
     * @return the value of l_order.totalprice
     *
     * @mbg.generated
     */
    public Double getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_order.totalprice
     *
     * @param totalprice the value for l_order.totalprice
     *
     * @mbg.generated
     */
    public void setTotalprice(Double totalprice) {
        this.totalprice = totalprice;
    }
}