package entity.user;

public class UserKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_user.uid
     *
     * @mbg.generated
     */
    private Integer uid;

   private String usalt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_user.uid
     *
     * @return the value of l_user.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    public String getUsalt() {
        return usalt;
    }

    public void setUsalt(String usalt) {
        this.usalt = usalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_user.uid
     *
     * @param uid the value for l_user.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }





}