package entity.staff;

import java.util.Date;

public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_car.car_id
     *
     * @mbg.generated
     */
    private Integer carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_car.car_name
     *
     * @mbg.generated
     */
    private String carName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_car.car_createtime
     *
     * @mbg.generated
     */
    private Date carCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_car.car_price
     *
     * @mbg.generated
     */
    private Double carPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_car.car_size
     *
     * @mbg.generated
     */
    private Integer carSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_car.car_nowLocation
     *
     * @mbg.generated
     */
    private Integer carNowlocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_car.car_lastLocation
     *
     * @mbg.generated
     */
    private Integer carLastlocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_car.car_nextLocation
     *
     * @mbg.generated
     */
    private Integer carNextlocation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_car.car_id
     *
     * @return the value of l_car.car_id
     *
     * @mbg.generated
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_car.car_id
     *
     * @param carId the value for l_car.car_id
     *
     * @mbg.generated
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_car.car_name
     *
     * @return the value of l_car.car_name
     *
     * @mbg.generated
     */
    public String getCarName() {
        return carName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_car.car_name
     *
     * @param carName the value for l_car.car_name
     *
     * @mbg.generated
     */
    public void setCarName(String carName) {
        this.carName = carName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_car.car_createtime
     *
     * @return the value of l_car.car_createtime
     *
     * @mbg.generated
     */
    public Date getCarCreatetime() {
        return carCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_car.car_createtime
     *
     * @param carCreatetime the value for l_car.car_createtime
     *
     * @mbg.generated
     */
    public void setCarCreatetime(Date carCreatetime) {
        this.carCreatetime = carCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_car.car_price
     *
     * @return the value of l_car.car_price
     *
     * @mbg.generated
     */
    public Double getCarPrice() {
        return carPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_car.car_price
     *
     * @param carPrice the value for l_car.car_price
     *
     * @mbg.generated
     */
    public void setCarPrice(Double carPrice) {
        this.carPrice = carPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_car.car_size
     *
     * @return the value of l_car.car_size
     *
     * @mbg.generated
     */
    public Integer getCarSize() {
        return carSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_car.car_size
     *
     * @param carSize the value for l_car.car_size
     *
     * @mbg.generated
     */
    public void setCarSize(Integer carSize) {
        this.carSize = carSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_car.car_nowLocation
     *
     * @return the value of l_car.car_nowLocation
     *
     * @mbg.generated
     */
    public Integer getCarNowlocation() {
        return carNowlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_car.car_nowLocation
     *
     * @param carNowlocation the value for l_car.car_nowLocation
     *
     * @mbg.generated
     */
    public void setCarNowlocation(Integer carNowlocation) {
        this.carNowlocation = carNowlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_car.car_lastLocation
     *
     * @return the value of l_car.car_lastLocation
     *
     * @mbg.generated
     */
    public Integer getCarLastlocation() {
        return carLastlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_car.car_lastLocation
     *
     * @param carLastlocation the value for l_car.car_lastLocation
     *
     * @mbg.generated
     */
    public void setCarLastlocation(Integer carLastlocation) {
        this.carLastlocation = carLastlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_car.car_nextLocation
     *
     * @return the value of l_car.car_nextLocation
     *
     * @mbg.generated
     */
    public Integer getCarNextlocation() {
        return carNextlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_car.car_nextLocation
     *
     * @param carNextlocation the value for l_car.car_nextLocation
     *
     * @mbg.generated
     */
    public void setCarNextlocation(Integer carNextlocation) {
        this.carNextlocation = carNextlocation;
    }
}