package entity.staff;

public class Cardetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_cardetail.carDetail_id
     *
     * @mbg.generated
     */
    private Integer cardetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_cardetail.car_id
     *
     * @mbg.generated
     */
    private Integer carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_cardetail.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_cardetail.carDetail_id
     *
     * @return the value of l_cardetail.carDetail_id
     *
     * @mbg.generated
     */
    public Integer getCardetailId() {
        return cardetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_cardetail.carDetail_id
     *
     * @param cardetailId the value for l_cardetail.carDetail_id
     *
     * @mbg.generated
     */
    public void setCardetailId(Integer cardetailId) {
        this.cardetailId = cardetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_cardetail.car_id
     *
     * @return the value of l_cardetail.car_id
     *
     * @mbg.generated
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_cardetail.car_id
     *
     * @param carId the value for l_cardetail.car_id
     *
     * @mbg.generated
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_cardetail.order_id
     *
     * @return the value of l_cardetail.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_cardetail.order_id
     *
     * @param orderId the value for l_cardetail.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
}