package entity.staff;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CarExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table l_car
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table l_car
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table l_car
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_car
     *
     * @mbg.generated
     */
    public CarExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_car
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_car
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_car
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_car
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_car
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_car
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_car
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_car
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_car
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_car
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table l_car
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCarIdIsNull() {
            addCriterion("car_id is null");
            return (Criteria) this;
        }

        public Criteria andCarIdIsNotNull() {
            addCriterion("car_id is not null");
            return (Criteria) this;
        }

        public Criteria andCarIdEqualTo(Integer value) {
            addCriterion("car_id =", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdNotEqualTo(Integer value) {
            addCriterion("car_id <>", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdGreaterThan(Integer value) {
            addCriterion("car_id >", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("car_id >=", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdLessThan(Integer value) {
            addCriterion("car_id <", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdLessThanOrEqualTo(Integer value) {
            addCriterion("car_id <=", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdIn(List<Integer> values) {
            addCriterion("car_id in", values, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdNotIn(List<Integer> values) {
            addCriterion("car_id not in", values, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdBetween(Integer value1, Integer value2) {
            addCriterion("car_id between", value1, value2, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdNotBetween(Integer value1, Integer value2) {
            addCriterion("car_id not between", value1, value2, "carId");
            return (Criteria) this;
        }

        public Criteria andCarNameIsNull() {
            addCriterion("car_name is null");
            return (Criteria) this;
        }

        public Criteria andCarNameIsNotNull() {
            addCriterion("car_name is not null");
            return (Criteria) this;
        }

        public Criteria andCarNameEqualTo(String value) {
            addCriterion("car_name =", value, "carName");
            return (Criteria) this;
        }

        public Criteria andCarNameNotEqualTo(String value) {
            addCriterion("car_name <>", value, "carName");
            return (Criteria) this;
        }

        public Criteria andCarNameGreaterThan(String value) {
            addCriterion("car_name >", value, "carName");
            return (Criteria) this;
        }

        public Criteria andCarNameGreaterThanOrEqualTo(String value) {
            addCriterion("car_name >=", value, "carName");
            return (Criteria) this;
        }

        public Criteria andCarNameLessThan(String value) {
            addCriterion("car_name <", value, "carName");
            return (Criteria) this;
        }

        public Criteria andCarNameLessThanOrEqualTo(String value) {
            addCriterion("car_name <=", value, "carName");
            return (Criteria) this;
        }

        public Criteria andCarNameLike(String value) {
            addCriterion("car_name like", value, "carName");
            return (Criteria) this;
        }

        public Criteria andCarNameNotLike(String value) {
            addCriterion("car_name not like", value, "carName");
            return (Criteria) this;
        }

        public Criteria andCarNameIn(List<String> values) {
            addCriterion("car_name in", values, "carName");
            return (Criteria) this;
        }

        public Criteria andCarNameNotIn(List<String> values) {
            addCriterion("car_name not in", values, "carName");
            return (Criteria) this;
        }

        public Criteria andCarNameBetween(String value1, String value2) {
            addCriterion("car_name between", value1, value2, "carName");
            return (Criteria) this;
        }

        public Criteria andCarNameNotBetween(String value1, String value2) {
            addCriterion("car_name not between", value1, value2, "carName");
            return (Criteria) this;
        }

        public Criteria andCarCreatetimeIsNull() {
            addCriterion("car_createtime is null");
            return (Criteria) this;
        }

        public Criteria andCarCreatetimeIsNotNull() {
            addCriterion("car_createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCarCreatetimeEqualTo(Date value) {
            addCriterion("car_createtime =", value, "carCreatetime");
            return (Criteria) this;
        }

        public Criteria andCarCreatetimeNotEqualTo(Date value) {
            addCriterion("car_createtime <>", value, "carCreatetime");
            return (Criteria) this;
        }

        public Criteria andCarCreatetimeGreaterThan(Date value) {
            addCriterion("car_createtime >", value, "carCreatetime");
            return (Criteria) this;
        }

        public Criteria andCarCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("car_createtime >=", value, "carCreatetime");
            return (Criteria) this;
        }

        public Criteria andCarCreatetimeLessThan(Date value) {
            addCriterion("car_createtime <", value, "carCreatetime");
            return (Criteria) this;
        }

        public Criteria andCarCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("car_createtime <=", value, "carCreatetime");
            return (Criteria) this;
        }

        public Criteria andCarCreatetimeIn(List<Date> values) {
            addCriterion("car_createtime in", values, "carCreatetime");
            return (Criteria) this;
        }

        public Criteria andCarCreatetimeNotIn(List<Date> values) {
            addCriterion("car_createtime not in", values, "carCreatetime");
            return (Criteria) this;
        }

        public Criteria andCarCreatetimeBetween(Date value1, Date value2) {
            addCriterion("car_createtime between", value1, value2, "carCreatetime");
            return (Criteria) this;
        }

        public Criteria andCarCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("car_createtime not between", value1, value2, "carCreatetime");
            return (Criteria) this;
        }

        public Criteria andCarPriceIsNull() {
            addCriterion("car_price is null");
            return (Criteria) this;
        }

        public Criteria andCarPriceIsNotNull() {
            addCriterion("car_price is not null");
            return (Criteria) this;
        }

        public Criteria andCarPriceEqualTo(Double value) {
            addCriterion("car_price =", value, "carPrice");
            return (Criteria) this;
        }

        public Criteria andCarPriceNotEqualTo(Double value) {
            addCriterion("car_price <>", value, "carPrice");
            return (Criteria) this;
        }

        public Criteria andCarPriceGreaterThan(Double value) {
            addCriterion("car_price >", value, "carPrice");
            return (Criteria) this;
        }

        public Criteria andCarPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("car_price >=", value, "carPrice");
            return (Criteria) this;
        }

        public Criteria andCarPriceLessThan(Double value) {
            addCriterion("car_price <", value, "carPrice");
            return (Criteria) this;
        }

        public Criteria andCarPriceLessThanOrEqualTo(Double value) {
            addCriterion("car_price <=", value, "carPrice");
            return (Criteria) this;
        }

        public Criteria andCarPriceIn(List<Double> values) {
            addCriterion("car_price in", values, "carPrice");
            return (Criteria) this;
        }

        public Criteria andCarPriceNotIn(List<Double> values) {
            addCriterion("car_price not in", values, "carPrice");
            return (Criteria) this;
        }

        public Criteria andCarPriceBetween(Double value1, Double value2) {
            addCriterion("car_price between", value1, value2, "carPrice");
            return (Criteria) this;
        }

        public Criteria andCarPriceNotBetween(Double value1, Double value2) {
            addCriterion("car_price not between", value1, value2, "carPrice");
            return (Criteria) this;
        }

        public Criteria andCarSizeIsNull() {
            addCriterion("car_size is null");
            return (Criteria) this;
        }

        public Criteria andCarSizeIsNotNull() {
            addCriterion("car_size is not null");
            return (Criteria) this;
        }

        public Criteria andCarSizeEqualTo(Integer value) {
            addCriterion("car_size =", value, "carSize");
            return (Criteria) this;
        }

        public Criteria andCarSizeNotEqualTo(Integer value) {
            addCriterion("car_size <>", value, "carSize");
            return (Criteria) this;
        }

        public Criteria andCarSizeGreaterThan(Integer value) {
            addCriterion("car_size >", value, "carSize");
            return (Criteria) this;
        }

        public Criteria andCarSizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("car_size >=", value, "carSize");
            return (Criteria) this;
        }

        public Criteria andCarSizeLessThan(Integer value) {
            addCriterion("car_size <", value, "carSize");
            return (Criteria) this;
        }

        public Criteria andCarSizeLessThanOrEqualTo(Integer value) {
            addCriterion("car_size <=", value, "carSize");
            return (Criteria) this;
        }

        public Criteria andCarSizeIn(List<Integer> values) {
            addCriterion("car_size in", values, "carSize");
            return (Criteria) this;
        }

        public Criteria andCarSizeNotIn(List<Integer> values) {
            addCriterion("car_size not in", values, "carSize");
            return (Criteria) this;
        }

        public Criteria andCarSizeBetween(Integer value1, Integer value2) {
            addCriterion("car_size between", value1, value2, "carSize");
            return (Criteria) this;
        }

        public Criteria andCarSizeNotBetween(Integer value1, Integer value2) {
            addCriterion("car_size not between", value1, value2, "carSize");
            return (Criteria) this;
        }

        public Criteria andCarNowlocationIsNull() {
            addCriterion("car_nowLocation is null");
            return (Criteria) this;
        }

        public Criteria andCarNowlocationIsNotNull() {
            addCriterion("car_nowLocation is not null");
            return (Criteria) this;
        }

        public Criteria andCarNowlocationEqualTo(Integer value) {
            addCriterion("car_nowLocation =", value, "carNowlocation");
            return (Criteria) this;
        }

        public Criteria andCarNowlocationNotEqualTo(Integer value) {
            addCriterion("car_nowLocation <>", value, "carNowlocation");
            return (Criteria) this;
        }

        public Criteria andCarNowlocationGreaterThan(Integer value) {
            addCriterion("car_nowLocation >", value, "carNowlocation");
            return (Criteria) this;
        }

        public Criteria andCarNowlocationGreaterThanOrEqualTo(Integer value) {
            addCriterion("car_nowLocation >=", value, "carNowlocation");
            return (Criteria) this;
        }

        public Criteria andCarNowlocationLessThan(Integer value) {
            addCriterion("car_nowLocation <", value, "carNowlocation");
            return (Criteria) this;
        }

        public Criteria andCarNowlocationLessThanOrEqualTo(Integer value) {
            addCriterion("car_nowLocation <=", value, "carNowlocation");
            return (Criteria) this;
        }

        public Criteria andCarNowlocationIn(List<Integer> values) {
            addCriterion("car_nowLocation in", values, "carNowlocation");
            return (Criteria) this;
        }

        public Criteria andCarNowlocationNotIn(List<Integer> values) {
            addCriterion("car_nowLocation not in", values, "carNowlocation");
            return (Criteria) this;
        }

        public Criteria andCarNowlocationBetween(Integer value1, Integer value2) {
            addCriterion("car_nowLocation between", value1, value2, "carNowlocation");
            return (Criteria) this;
        }

        public Criteria andCarNowlocationNotBetween(Integer value1, Integer value2) {
            addCriterion("car_nowLocation not between", value1, value2, "carNowlocation");
            return (Criteria) this;
        }

        public Criteria andCarLastlocationIsNull() {
            addCriterion("car_lastLocation is null");
            return (Criteria) this;
        }

        public Criteria andCarLastlocationIsNotNull() {
            addCriterion("car_lastLocation is not null");
            return (Criteria) this;
        }

        public Criteria andCarLastlocationEqualTo(Integer value) {
            addCriterion("car_lastLocation =", value, "carLastlocation");
            return (Criteria) this;
        }

        public Criteria andCarLastlocationNotEqualTo(Integer value) {
            addCriterion("car_lastLocation <>", value, "carLastlocation");
            return (Criteria) this;
        }

        public Criteria andCarLastlocationGreaterThan(Integer value) {
            addCriterion("car_lastLocation >", value, "carLastlocation");
            return (Criteria) this;
        }

        public Criteria andCarLastlocationGreaterThanOrEqualTo(Integer value) {
            addCriterion("car_lastLocation >=", value, "carLastlocation");
            return (Criteria) this;
        }

        public Criteria andCarLastlocationLessThan(Integer value) {
            addCriterion("car_lastLocation <", value, "carLastlocation");
            return (Criteria) this;
        }

        public Criteria andCarLastlocationLessThanOrEqualTo(Integer value) {
            addCriterion("car_lastLocation <=", value, "carLastlocation");
            return (Criteria) this;
        }

        public Criteria andCarLastlocationIn(List<Integer> values) {
            addCriterion("car_lastLocation in", values, "carLastlocation");
            return (Criteria) this;
        }

        public Criteria andCarLastlocationNotIn(List<Integer> values) {
            addCriterion("car_lastLocation not in", values, "carLastlocation");
            return (Criteria) this;
        }

        public Criteria andCarLastlocationBetween(Integer value1, Integer value2) {
            addCriterion("car_lastLocation between", value1, value2, "carLastlocation");
            return (Criteria) this;
        }

        public Criteria andCarLastlocationNotBetween(Integer value1, Integer value2) {
            addCriterion("car_lastLocation not between", value1, value2, "carLastlocation");
            return (Criteria) this;
        }

        public Criteria andCarNextlocationIsNull() {
            addCriterion("car_nextLocation is null");
            return (Criteria) this;
        }

        public Criteria andCarNextlocationIsNotNull() {
            addCriterion("car_nextLocation is not null");
            return (Criteria) this;
        }

        public Criteria andCarNextlocationEqualTo(Integer value) {
            addCriterion("car_nextLocation =", value, "carNextlocation");
            return (Criteria) this;
        }

        public Criteria andCarNextlocationNotEqualTo(Integer value) {
            addCriterion("car_nextLocation <>", value, "carNextlocation");
            return (Criteria) this;
        }

        public Criteria andCarNextlocationGreaterThan(Integer value) {
            addCriterion("car_nextLocation >", value, "carNextlocation");
            return (Criteria) this;
        }

        public Criteria andCarNextlocationGreaterThanOrEqualTo(Integer value) {
            addCriterion("car_nextLocation >=", value, "carNextlocation");
            return (Criteria) this;
        }

        public Criteria andCarNextlocationLessThan(Integer value) {
            addCriterion("car_nextLocation <", value, "carNextlocation");
            return (Criteria) this;
        }

        public Criteria andCarNextlocationLessThanOrEqualTo(Integer value) {
            addCriterion("car_nextLocation <=", value, "carNextlocation");
            return (Criteria) this;
        }

        public Criteria andCarNextlocationIn(List<Integer> values) {
            addCriterion("car_nextLocation in", values, "carNextlocation");
            return (Criteria) this;
        }

        public Criteria andCarNextlocationNotIn(List<Integer> values) {
            addCriterion("car_nextLocation not in", values, "carNextlocation");
            return (Criteria) this;
        }

        public Criteria andCarNextlocationBetween(Integer value1, Integer value2) {
            addCriterion("car_nextLocation between", value1, value2, "carNextlocation");
            return (Criteria) this;
        }

        public Criteria andCarNextlocationNotBetween(Integer value1, Integer value2) {
            addCriterion("car_nextLocation not between", value1, value2, "carNextlocation");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table l_car
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table l_car
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}