package entity.staff;

public class Locationdetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_locationdetail.lDetail_id
     *
     * @mbg.generated
     */
    private Integer ldetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_locationdetail.location_id
     *
     * @mbg.generated
     */
    private Integer locationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_locationdetail.lDetail_id
     *
     * @return the value of l_locationdetail.lDetail_id
     *
     * @mbg.generated
     */
    public Integer getLdetailId() {
        return ldetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_locationdetail.lDetail_id
     *
     * @param ldetailId the value for l_locationdetail.lDetail_id
     *
     * @mbg.generated
     */
    public void setLdetailId(Integer ldetailId) {
        this.ldetailId = ldetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_locationdetail.location_id
     *
     * @return the value of l_locationdetail.location_id
     *
     * @mbg.generated
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_locationdetail.location_id
     *
     * @param locationId the value for l_locationdetail.location_id
     *
     * @mbg.generated
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }
}