package entity.staff;

public class Location {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_location.location_id
     *
     * @mbg.generated
     */
    private Integer locationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_location.location_name
     *
     * @mbg.generated
     */
    private String locationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_location.staff_number
     *
     * @mbg.generated
     */
    private Integer staffNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_location.location_id
     *
     * @return the value of l_location.location_id
     *
     * @mbg.generated
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_location.location_id
     *
     * @param locationId the value for l_location.location_id
     *
     * @mbg.generated
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_location.location_name
     *
     * @return the value of l_location.location_name
     *
     * @mbg.generated
     */
    public String getLocationName() {
        return locationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_location.location_name
     *
     * @param locationName the value for l_location.location_name
     *
     * @mbg.generated
     */
    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_location.staff_number
     *
     * @return the value of l_location.staff_number
     *
     * @mbg.generated
     */
    public Integer getStaffNumber() {
        return staffNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_location.staff_number
     *
     * @param staffNumber the value for l_location.staff_number
     *
     * @mbg.generated
     */
    public void setStaffNumber(Integer staffNumber) {
        this.staffNumber = staffNumber;
    }
}