package entity.staff;

public class Staff {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_staff.staff_id
     *
     * @mbg.generated
     */
    private Integer staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_staff.staff_name
     *
     * @mbg.generated
     */
    private String staffName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_staff.staff_password
     *
     * @mbg.generated
     */
    private String staffPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_staff.staff_location
     *
     * @mbg.generated
     */
    private Integer staffLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_staff.staff_sex
     *
     * @mbg.generated
     */
    private Boolean staffSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_staff.staff_age
     *
     * @mbg.generated
     */
    private Byte staffAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_staff.staff_phone
     *
     * @mbg.generated
     */
    private String staffPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_staff.staff_mail
     *
     * @mbg.generated
     */
    private String staffMail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_staff.staff_id
     *
     * @return the value of l_staff.staff_id
     *
     * @mbg.generated
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_staff.staff_id
     *
     * @param staffId the value for l_staff.staff_id
     *
     * @mbg.generated
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_staff.staff_name
     *
     * @return the value of l_staff.staff_name
     *
     * @mbg.generated
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_staff.staff_name
     *
     * @param staffName the value for l_staff.staff_name
     *
     * @mbg.generated
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_staff.staff_password
     *
     * @return the value of l_staff.staff_password
     *
     * @mbg.generated
     */
    public String getStaffPassword() {
        return staffPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_staff.staff_password
     *
     * @param staffPassword the value for l_staff.staff_password
     *
     * @mbg.generated
     */
    public void setStaffPassword(String staffPassword) {
        this.staffPassword = staffPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_staff.staff_location
     *
     * @return the value of l_staff.staff_location
     *
     * @mbg.generated
     */
    public Integer getStaffLocation() {
        return staffLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_staff.staff_location
     *
     * @param staffLocation the value for l_staff.staff_location
     *
     * @mbg.generated
     */
    public void setStaffLocation(Integer staffLocation) {
        this.staffLocation = staffLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_staff.staff_sex
     *
     * @return the value of l_staff.staff_sex
     *
     * @mbg.generated
     */
    public Boolean getStaffSex() {
        return staffSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_staff.staff_sex
     *
     * @param staffSex the value for l_staff.staff_sex
     *
     * @mbg.generated
     */
    public void setStaffSex(Boolean staffSex) {
        this.staffSex = staffSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_staff.staff_age
     *
     * @return the value of l_staff.staff_age
     *
     * @mbg.generated
     */
    public Byte getStaffAge() {
        return staffAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_staff.staff_age
     *
     * @param staffAge the value for l_staff.staff_age
     *
     * @mbg.generated
     */
    public void setStaffAge(Byte staffAge) {
        this.staffAge = staffAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_staff.staff_phone
     *
     * @return the value of l_staff.staff_phone
     *
     * @mbg.generated
     */
    public String getStaffPhone() {
        return staffPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_staff.staff_phone
     *
     * @param staffPhone the value for l_staff.staff_phone
     *
     * @mbg.generated
     */
    public void setStaffPhone(String staffPhone) {
        this.staffPhone = staffPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_staff.staff_mail
     *
     * @return the value of l_staff.staff_mail
     *
     * @mbg.generated
     */
    public String getStaffMail() {
        return staffMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_staff.staff_mail
     *
     * @param staffMail the value for l_staff.staff_mail
     *
     * @mbg.generated
     */
    public void setStaffMail(String staffMail) {
        this.staffMail = staffMail;
    }
}