package entity.staff;

public class Super {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_super.super_id
     *
     * @mbg.generated
     */
    private Integer superId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_super.super_id
     *
     * @return the value of l_super.super_id
     *
     * @mbg.generated
     */
    public Integer getSuperId() {
        return superId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_super.super_id
     *
     * @param superId the value for l_super.super_id
     *
     * @mbg.generated
     */
    public void setSuperId(Integer superId) {
        this.superId = superId;
    }
}